# Generated by Django 3.0.3 on 2020-02-16 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPageGalleryImage',
        ),
    ]
